---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Create group ops with gid 1234
    getent:
      database: group
      split: ':'
    register: result

  - debug:
      var: result.ansible_facts.getent_group

  - name: "Show file path only"
    debug:
      msg:
        - "Group: {{ item.key }}"
        - "gid: {{ item.value.1 }}"
        - "users: {{ item.value.2.split(',') }}"
    loop: "{{ result.ansible_facts.getent_group | dict2items }}"
    when: item.value.1 | int > 1000

  - name: Ensure group is present
    community.general.ipa_group:
      name: "{{ item.key }}"
      gidnumber: "{{ item.value.1 }}"
      state: present
      ipa_host: idm.ocp4.cfernand.sergio.link
      ipa_user: admin
      ipa_pass: redhat2020
    loop: "{{ result.ansible_facts.getent_group | dict2items }}"
    when: item.value.1 | int > 1000
