---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Create group ops with gid 1234
    getent:
      database: group
      split: ':'
    register: result

  - name: Ensure that users linus and larry are assign to the group, but no other user
    ipa_group:
      name: "{{ item.key }}"
      gidnumber: "{{ item.value.1 }}"
      user: "{{ item.value.2.split(',') }}"
      ipa_host: idm.ocp4.cfernand.sergio.link
      ipa_user: admin
      ipa_pass: redhat2020
    loop: "{{ result.ansible_facts.getent_group | dict2items }}"
    when: item.value.1 | int > 1000

